# Generated by Django 5.2.6 on 2025-10-01 21:38

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=apps.core.fields.HybridImageField(
                blank=True,
                help_text="Category image - can be a local file or remote URL",
                max_length=None,
                null=True,
                upload_to="categories/images/",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="featured_image",
            field=apps.core.fields.HybridImageField(
                blank=True,
                help_text="Primary product image - can be a local file or remote URL",
                max_length=None,
                null=True,
                upload_to="products/images/",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=apps.core.fields.HybridImageField(
                help_text="Product image - can be a local file or remote URL",
                max_length=None,
                upload_to="products/gallery/",
            ),
        ),
    ]
